--Inicio DDL - InLock_Games_Tarde

CREATE DATABASE InLock_Games_Tarde
GO

USE InLock_Games_Tarde
GO

CREATE TABLE Estudio(
idEstudio SMALLINT PRIMARY KEY IDENTITY, 
nomeEstudio VARCHAR (50) UNIQUE NOT NULL,
);
GO

CREATE TABLE TipoUsuario(
idTipouser INT PRIMARY KEY IDENTITY,
Titulo VARCHAR (20) NOT NULL,
);
GO

CREATE TABLE Jogo(
idJogo INT PRIMARY KEY IDENTITY,
idEstudio SMALLINT FOREIGN KEY REFERENCES Estudio(idEstudio),
nomeJogo VARCHAR (40) UNIQUE NOT NULL,
DataLan DATE NOT NULL,
Valor SMALLMONEY NOT NULL,
Descricao VARCHAR (300) NOT NULL,
);
GO

CREATE TABLE Usuario(
idUsuario INT PRIMARY KEY IDENTITY,
idTipoUser INT FOREIGN KEY REFERENCES TipoUsuario(idTipoUser),
Email VARCHAR (100) UNIQUE NOT NULL,
Senha CHAR (10) NOT NULL, 
);
GO
